### PR TITLE
🎶 Audio Player + ✒ Organise files is the best thing in coding 🙆‍♂️

### PR DESCRIPTION
**Pull request by yassinrais**
+ Audio Player ( test mp3 https://gofile.io/d/kFnIU1 )
+ Add Simple Style for admin
+ Fix Page scrollbar ( hidden : canvas is full screen ) 
+ Move js to assets/js  folder , css to assets/css
+ HTML Meta Tags

### CODE REVIEW

**Comment by shiffman** [comment]
Hey @yassinrais, this is amazing! Would you mind separating out the audio and the other improvements into two pull requests? I love the idea of an option for sound but the way I'm using it right now the sound wouldn't play (OBS -> Zoom) so prefer to hold off until later?

@all-contributors add @yassinrais for code and ideas!

**Comment by yassinrais** [comment]
@shiffman  , Of course, even me, I think about this at the last commit , I should create different version to make it easy to understand for others :D 👥 .

**Comment by yassinrais** [comment]
I will close this pull request and request a new one with less modification & refork the respository again 😅 sorry for this conflits issues

**Comment by ShawKai91** [comment]
that's why i tried working them into mine

if only i could do that and still have it credit you
Ive tried merging yours into mine but couldn't figured out how

**Comment by yassinrais** [comment]
Same issue with me  , i cant marged yours with mine , im not to expert in git merge with diffirent forks

**Pull request closed without merging**
