### PR TITLE
🗃 Organise files/assets

### PR DESCRIPTION
**Pull request by yassinrais**

### CODE REVIEW

**Comment by shiffman** [comment]
@yassinrais this ended up with some merge conflicts. I see that @ShawKai91 incorporated these ideas in #14, however it would be great to fix them up here so that the repo history can properly credit @yassinrais!

**Comment by yassinrais** [comment]
@shiffman im trying to fix this issue

**Comment by yassinrais** [comment]
Im not sur why this still has conflicts and in #14 the are no conflit , im not to good at git conflicts , if you can help to fix this it will be good 😅

**Comment by ShawKai91** [comment]
i could put them back into mine with the commit of 'styles + structure by  yassinrais'
or you can re branch and try again

side note - writing the above gave me the biggest sense of daja vu

**Comment by yassinrais** [comment]
I can repull a new reuqest after your merging :) , those branch will be closed, if you have any other solution tell me , before i totaly close those pulls

**Comment by ShawKai91** [comment]
id go ahead and close.
and at lest re fork to try and resolve the conflicts

it sometimes gives me the option to resolve conflicts right there and others it says do it in cli

**Comment by shiffman** [comment]
I resolved the conflicts and merged!

**Pull request merged**
