### PR TITLE
Changing the loop to show the particles into an in loop

### PR DESCRIPTION
**Pull request by iKittyCode**

### CODE REVIEW

**Comment by shiffman** [comment]
Hi @iKittyCode thanks for this contribution! Can you say more about this change? I typically prefer to use the more standard `for` loop, perhaps I am old fashioned!

**Comment by shiffman** [comment]
@all-contributors add @iKittyCode for ideas

**Comment by iKittyCode** [comment]
this loop might be more secure because there can't be an infinite loop.
Take this for example:
var Greetings = ["Hi", "Hello", "How you doing"]
// This is an infinite loop
for (var i = 0; i > 0; i++) {
Greetings.push("Whats your name")

}
Edited version:
    var Greetings = ["Hi", "Hello", "How you doing"]
// This is not an infinite loop
for (var i in Greetings) {
Greetings.push("Whats your name")

}

**Comment by shiffman** [comment]
Thanks for the explanation @iKittyCode! I think I will leave it as a regular `for` loop just to match my previous Nature of Code examples but I will consider your suggestions for future examples!

**Pull request closed without merging**
